---
- name: Deploy Docker image
  connection: local   
  become: true
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull the PocketBase Docker image
      docker_image:
        name: augustodelg/pocketbase
        source: pull
        tag: latest

    - name: Run PocketBase container
      docker_container:
        name: pocketbase
        image: augustodelg/pocketbase:latest
        state: started
        restart_policy: always
