---
- name: Build and run PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-{{ pb_version }}"
        source: build
        build:
          path: .
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true

    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ host_name }}"
        image: "pocketbase-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        ports:
          - "{{ port }}:8090"
