- name: Install Caddy Server in Docker
  hosts: localhost
  become: true

  tasks:
    - name: Ensure Docker is installed
      become: true
      apt:
        name: docker.io
        state: present

    - name: Pull Caddy image
      docker_image:
        name: caddy:latest
        state: present

    - name: Create a Caddyfile
      template:
        src: caddyfile.j2
        dest: /tmp/Caddyfile
        mode: 0644

    - name: Run Caddy in a Docker container
      docker_container:
        name: my-caddy-container
        image: caddy:latest
        state: started
        ports:
          - published: 80
            target: 80
        volumes:
          - /tmp/Caddyfile:/etc/caddy/Caddyfile:ro

    - name: Verify Caddy is running
      shell: docker ps | grep my-caddy-container
      register: container_status
    - assert:
        that: container_status.stdout.find("my-caddy-container") >= 0
        msg: "Caddy container is not running"
