- name: Install Caddy Server in Docker
  hosts: all
  local: true

  tasks:
    - name: Pull Caddy image
      docker_image:
        name: caddy:latest
        state: present

    - name: Create a Caddyfile
      template:
        src: caddyfile.j2
        dest: /tmp/Caddyfile
        mode: 0644

    - name: Run Caddy in a Docker container
      docker_container:
        name: caddyserver
        image: caddy:latest
        state: started
        ports:
          - published: 80
            target: 80
        volumes:
          - /tmp/Caddyfile:/etc/caddy/Caddyfile:ro
