- name: Install Caddy Server
  hosts: all
  local: true

  tasks:
    - name: Pull Caddy image
      docker_image:
        name: caddy:latest
        state: present

    - name: Run Caddy in a Docker container
      docker_container:
        name: caddyserver
        image: caddy:latest
        state: started
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"

        volumes:
          - "{{ coddy_dir }}/Caddyfile:/etc/caddy/Caddyfile"
          - "{{ coddy_dir }}/site:/srv"
          - "{{ coddy_dir }}:/data"
          - "{{ coddy_dir }}:/config"
        
